import assert from 'node:assert/strict';
const base = process.env.TEST_ORIGIN || 'http://127.0.0.1:8787';
const identity = {'oai-authenticated-user-id':'test-romain', 'oai-authenticated-user-email':'test@example.invalid'};
const get = (headers={}) => fetch(base+'/api/sectors',{headers});
const put = (data,headers=identity,origin=base) => fetch(base+'/api/sectors',{method:'PUT',headers:{...headers,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(data)});
assert.equal((await get()).status,401,'anonymous API rejected');
assert.equal((await put({} ,{})).status,401,'anonymous write rejected');
const root = await fetch(base+'/',{redirect:'manual'});
assert.equal(root.status,307,'private page redirects');
assert.match(root.headers.get('location'),/signin-with-chatgpt/);
assert.equal((await fetch(base+'/vitrine')).status,200,'showcase renders');
assert.equal((await fetch(base+'/',{headers:identity})).status,200,'dashboard renders for identity');
let r = await get(identity); assert.equal(r.status,200);
assert.match(r.headers.get('cache-control'),/no-store/);
let rows = await r.json(); assert.equal(rows.length,10); assert.equal(new Set(rows.map(s=>s.id)).size,10);
assert.ok(rows.every(s=>s.criteria.length===3 && s.offers.length>=2));
let s = rows.find(s=>s.id==='architecture');
const payload = {id:s.id,priority:2,status:'En réflexion',notes:'Contrôle persistance — échantillon fictif',version:s.version};
assert.equal((await put(payload,identity,'https://untrusted.invalid')).status,403,'cross-origin write rejected');
assert.equal((await put({...payload,priority:99})).status,400,'invalid priority rejected');
assert.equal((await put({...payload,notes:'x'.repeat(10001)})).status,400,'long note rejected');
r = await put(payload); assert.equal(r.status,200); const saved=await r.json();
const again = await (await get({...identity})).json(); const row=again.find(x=>x.id===s.id);
assert.equal(row.notes,payload.notes); assert.equal(row.priority,2); assert.equal(row.status,'En réflexion'); assert.equal(row.version,saved.version);
assert.equal((await put(payload)).status,409,'stale update rejected');
const other = await (await get({'oai-authenticated-user-id':'test-other','oai-authenticated-user-email':'other@example.invalid'})).json();
assert.equal(other.find(x=>x.id===s.id).notes,'','notes isolated between users');
r=await put({...payload,notes:s.notes,priority:s.priority,status:s.status,version:saved.version});assert.equal(r.status,200,'restore fixture');
console.log('PASS: 15 API, authorization, validation, persistence and page-render checks. No browser QA.');

