import type { RadarResult } from './types.ts';

const escapeJson = (value: unknown) =>
  JSON.stringify(value).replace(/</g, '\\u003c').replace(/-->/g, '--\\u003e');

export function buildRadarUiHtml(
  initialData: RadarResult | null = null,
  previewState:
    | 'results'
    | 'loading'
    | 'empty'
    | 'error'
    | 'live'
    | null = null,
) {
  return `<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Radar local</title><style>
:root{color-scheme:light dark;--bg:var(--color-background-primary,#fff);--surface:var(--color-background-secondary,#f7f7f5);--text:var(--color-text-primary,#20211f);--muted:var(--color-text-secondary,#666963);--line:var(--color-border-secondary,#dadbd6);--accent:#d94d28;--accent-soft:#fff0e9;--good:#176b55;--good-soft:#e7f5ef;--warn:#805c05;--warn-soft:#fff5d6;font-family:var(--font-sans,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif)}
@media(prefers-color-scheme:dark){:root{--bg:#151817;--surface:#1e2321;--text:#f3f3ef;--muted:#aeb4b0;--line:#38413e;--accent:#ff7955;--accent-soft:#3d271f;--good:#83d7b8;--good-soft:#17392e;--warn:#e5bd61;--warn-soft:#3a321b}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-size:14px;line-height:1.45}.radar{padding:16px;max-width:760px;margin:auto}.eyebrow{display:flex;align-items:center;gap:8px;color:var(--accent);font-weight:700;font-size:12px;letter-spacing:.08em;text-transform:uppercase}.ping{width:9px;height:9px;border:2px solid currentColor;border-radius:50%;position:relative}.ping:after{content:"";position:absolute;width:1px;height:18px;background:currentColor;left:3px;top:-6px;transform:rotate(42deg)}h1{font-size:20px;line-height:1.2;margin:8px 0 3px;letter-spacing:-.02em}.subtitle{margin:0;color:var(--muted);font-size:13px}.cards{display:grid;gap:9px;margin-top:14px}.card{border:1px solid var(--line);background:var(--surface);padding:13px;border-radius:12px}.top{display:flex;gap:10px;align-items:flex-start;justify-content:space-between}.name{font-size:15px;font-weight:750;line-height:1.25}.place{color:var(--muted);font-size:12px;margin-top:2px}.badge{white-space:nowrap;border-radius:999px;padding:4px 8px;font-size:11px;font-weight:700;background:var(--warn-soft);color:var(--warn)}.badge.priority{background:var(--good-soft);color:var(--good)}.activity{margin-top:9px;font-weight:650}.meta{color:var(--muted);font-size:12px;margin-top:2px}.explain{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.label{display:block;font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:var(--muted);font-weight:700;margin-bottom:2px}.explain p{margin:0;font-size:12px}.actions{display:flex;gap:8px;margin-top:11px}.actions button{border:1px solid var(--line);background:transparent;color:var(--text);border-radius:8px;padding:7px 9px;font:inherit;font-size:12px;font-weight:650;cursor:pointer}.actions button.primary{border-color:var(--accent);color:var(--accent)}.more{display:block;margin:10px auto 0;border:0;background:transparent;color:var(--accent);font:inherit;font-weight:700;cursor:pointer;padding:7px}.state{border:1px dashed var(--line);border-radius:12px;padding:24px;text-align:center;color:var(--muted);margin-top:14px}.test{display:inline-block;margin-top:8px;padding:3px 7px;border-radius:5px;background:var(--warn-soft);color:var(--warn);font-size:11px;font-weight:700}.hidden{display:none}@media(max-width:560px){.radar{padding:12px}.explain{grid-template-columns:1fr}.top{display:block}.badge{display:inline-block;margin-top:7px}.actions{flex-wrap:wrap}}
</style></head><body><main class="radar"><div class="eyebrow"><span class="ping"></span>Radar local</div><div id="root"><div class="state">Recherche des entreprises publiques…</div></div></main>
<script>
const INITIAL=${escapeJson(initialData)};const PREVIEW_STATE=${escapeJson(previewState)};const PREVIEW=!!PREVIEW_STATE;let nextId=1;const pending=new Map();
function rpc(method,params){if(PREVIEW)return Promise.resolve({});const id=nextId++;parent.postMessage({jsonrpc:'2.0',id,method,params},'*');return new Promise((resolve,reject)=>pending.set(id,{resolve,reject}))}
function notify(method,params){if(!PREVIEW)parent.postMessage({jsonrpc:'2.0',method,params},'*')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function card(company,index){const extra=index>2?' extra hidden':'';const badge=company.niveauPriorite==='Prioritaire'?'priority':'';return '<article class="card'+extra+'"><div class="top"><div><div class="name">'+esc(company.nom)+'</div><div class="place">'+esc(company.commune)+' · '+esc(company.distanceKm)+' km</div></div><span class="badge '+badge+'">'+esc(company.niveauPriorite)+'</span></div><div class="activity">'+esc(company.activiteLibelle)+'</div><div class="meta">'+esc(company.trancheEffectif)+(company.nombreEtablissements>1?' · '+esc(company.nombreEtablissements)+' établissements actifs':'')+'</div><div class="explain"><p><span class="label">Pourquoi elle ressort</span>'+esc(company.raisonSelection)+'</p><p><span class="label">Angle de démonstration possible</span>'+esc(company.workflowProbable)+'</p></div><div class="actions"><button data-url="'+esc(company.sourceUrl)+'">Voir la fiche officielle</button><button class="primary" data-company="'+esc(company.nom)+'" data-siren="'+esc(company.siren)+'">Creuser cette entreprise</button></div></article>'}
function render(result){const root=document.getElementById('root');if(!result||!Array.isArray(result.companies)){root.innerHTML='<div class="state">Les résultats reçus sont invalides.</div>';return}const count=result.companies.length;if(!count){root.innerHTML='<h1>Aucune entreprise trouvée</h1><p class="subtitle">Essayez un rayon plus large ou d’autres secteurs.</p>';return}root.innerHTML='<h1>'+count+' entreprise'+(count>1?'s':'')+' à examiner autour de Vairé</h1><p class="subtitle">Sélectionnées pour tester un workflow de réclamation client. Besoin réel à confirmer.</p>'+(PREVIEW_STATE&&PREVIEW_STATE!=='live'?'<span class="test">Données de test</span>':'')+'<section class="cards">'+result.companies.map(card).join('')+'</section>'+(count>3?'<button class="more" id="more">Afficher les '+(count-3)+' suivantes</button>':'');root.querySelectorAll('[data-url]').forEach(b=>b.onclick=()=>PREVIEW?window.open(b.dataset.url,'_blank','noopener'):rpc('ui/open-link',{url:b.dataset.url}));root.querySelectorAll('[data-company]').forEach(b=>b.onclick=()=>{const text='Analyse plus précisément l’entreprise '+b.dataset.company+' (SIREN '+b.dataset.siren+') et cherche uniquement des informations publiques permettant de comprendre son activité, son organisation et ses workflows probables. Distingue les faits des hypothèses.';if(PREVIEW){b.textContent='Message prêt pour ChatGPT';return}rpc('ui/message',{role:'user',content:[{type:'text',text}]})});const more=document.getElementById('more');if(more)more.onclick=()=>{root.querySelectorAll('.extra').forEach(e=>e.classList.remove('hidden'));more.remove()}}
addEventListener('message',event=>{const m=event.data;if(!m||m.jsonrpc!=='2.0')return;if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);return}if(m.method==='ui/notifications/tool-result'){const p=m.params||{};if(p.isError){document.getElementById('root').innerHTML='<div class="state">La recherche a échoué. Réessayez dans quelques instants.</div>'}else render(p.structuredContent)}});
if(PREVIEW_STATE==='error')document.getElementById('root').innerHTML='<div class="state">La source publique est momentanément inaccessible. Réessayez plus tard.</div>';else if(PREVIEW_STATE==='empty')render({...INITIAL,companies:[]});else if(PREVIEW_STATE==='results'||PREVIEW_STATE==='live')render(INITIAL);else if(!PREVIEW_STATE)rpc('ui/initialize',{protocolVersion:'2026-01-26',appInfo:{name:'radar-local',version:'1.0.0'},appCapabilities:{}}).then(result=>{const vars=result&&result.hostContext&&result.hostContext.styles&&result.hostContext.styles.variables;if(vars)Object.entries(vars).forEach(([k,v])=>document.documentElement.style.setProperty(k,v));if(result&&result.hostContext&&result.hostContext.theme)document.documentElement.style.colorScheme=result.hostContext.theme;notify('ui/notifications/initialized',{})}).catch(()=>{document.getElementById('root').innerHTML='<div class="state">Impossible d’initialiser l’affichage Radar local.</div>'});
</script></body></html>`;
}
